name: EUnit

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [19.3.6, 20.3.8.26, 21.3.8.16, 22.3.4.2, 23.0.2]
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.0.0
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: compile
      run: rebar3 compile

    - name: test
      run: rebar3 eunit
